### ISSUE TITLE
How do we change the hashes in the files so we can have a theoretical translation for Kakao?

### ISSUE THREAD

**Issue by PinkSheep752** [barncastle/CookieRun-DJBF-Converter#5]
I bet that we have everything that we need for a KCR translation, but the main problem is trying to execute it all properly… if you know how to do it, then please talk to me on Discord. Tag is PinkSheep752#5249

**Comment by probperiplum** [comment]
I will be making a more in-depth comment on resources and what specifically PinkSheep752 is requesting here as I believe directing someone to be DMed on discord goes against discoverability for those curious about this as well.

In Cookie Run for Kakao; in the APK or IPA, a index.json file exists that is stored in the assets folder on Android or the Payload (essentially root of app assets) folder on iOS. When the game is downloaded, the index.json file is in the root/data/data/com.devsisters.CookieRunForKakao/patch folder on Android. The index.json file from the lastest online patch for the latest version of Cookie Run for Kakao, 9.22; can be found here: https://cdn.discordapp.com/attachments/625526165419065385/1027788354370146386/index.json (the game has not been updated in years so it is unlikely it will change any time soon, but I could be wrong)

The index.json file lists all of the files present in the assets folder and assigns them SHA-1 hashes, where the assets are checked upon boot. For .djb files exclusively, the game will redownload them if it detects the hash is incorrect, while the hash checked images or plists are generally not redownloaded if removed or tampered with manually. It is theorized that the hashes are responsible for the redownloading of replaced .djb files, even if the encryption is otherwise okay. This has been a roadblock for people who wish to have an English version of Cookie Run for Kakao, intimidated by the Korean menus and text.

Official translation work of Cookie Run for Kakao has been done and released under LINE Cookie Run, which had it's files preserved. Fans have attempted to make "English patches" of Cookie Run for Kakao by replacing the Korean-specific images and text within the .apk, though these attempts have had limited success. While the game does accept and read the loading messages in English, it will redownload the original Korean .djbs while having the images and plists otherwise remain intact. An English version of Cookie Run for Kakao has been somewhat of a wishful thought after LINE Cookie Run had closed, leaving Cookie Run for Kakao the only way to play essentially the same game but with a language barrier. It's not *impossible* to play the game without translation, but it is frustrating to many.

Syrrupypluto (https://github.com/syrupyy) has commented offsite on the manner and has stated a possible theory on how to get around to making the game accept new index.json files. The quote is as follows:

"you will need to decrypt the index, edit the hashes and size, reencrypt the index and use a proxy to serve the modified index to the game"

As many average users would probably not know what to do with a proxy without some sort of guidance, another proposed idea is to just somehow figure out a way to make the game have a replaced index.json file where the hashes can be replaced with modified files' new hashes so the game can read them and make the game easier to understand to English-speaking players.

I know this is a lot, but this is the context I have. If you nees something like a copy of the LINE Cookie Run translated .djb files, I will be happy to provide them.

**Comment by PinkSheep752** [comment]
Isn't the latest version of Kakao 10.02? Or does that one not have an index.json file?

**Comment by probperiplum** [comment]
I think it is, that was a mistake on my part

**Comment by PinkSheep752** [comment]
@barncastle can you try and respond to us as soon as you can? Or better, we have a Discord for modding all things Cookie Run (besides CROB, Kingdom, and Puzzle World as those are still operating): https://discord.gg/RSUBnMRguh

**Comment by barncastle** [comment]
This is well outside the scope of this tool - which is to decrypt/encrypt DJB files. In terms of generating SHA-1 hashes of files, there's a multitude of tools and websites out there and is even supported in bash and PowerShell however the rest sounds like a major project and is not something I'd be interested in pursuing.

With that being said, my initial thoughts based on @probperiplum's comment is:
1. Disable internet connectivity and see if it works - not sure the game would even run.
2. Patch the `index.json` URL to point to a custom one.
3. Patch the APK to skip the checksum check altogether.
