### ISSUE TITLE
is it possible to change with more characters on v3 encryption djb file?

### ISSUE THREAD

**Issue by ghost** [barncastle/CookieRun-DJBF-Converter#8]
I want to change 

cookierun/ingame/Char_Jump_ch01 -> cookierun/InGame_Ch01/Char_Jump_ch01

that on 6,04 CRXSoundEventList.djb file, but when I change with hxd, game crash(I think because of file size changed, if I don't change file size, then it does not crash). this change increase character length (31 -> 36) so I am unable to not change file size.

Do you know how to solve it?

**Comment by barncastle** [comment]
Did you update the string length as per my [documentation](https://github.com/barncastle/CookieRun-DJBF-Converter/issues/3#issuecomment-1268252479)? 

The new string is 36 characters, which is `24 00 00 00` in 32-bit hex which is what the previous 4 bytes need to be (https://ibb.co/dBcsyMX). 

If you have and it still crashes, then I'd try testing with another sound which you know is valid but a different length first e.g., `cookierun/ingame/SoundEff_BardDestruction`. This will indicate if the issue is with the new `InGame_CH01` path.
